// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUYihWNw3PG_VGQQ6CVk07Cv_WT2gsCJ8',
    appId: '1:869303010677:web:6b29c013162057d86aff3c',
    messagingSenderId: '869303010677',
    projectId: 'zomaato-a64ad',
    authDomain: 'zomaato-a64ad.firebaseapp.com',
    storageBucket: 'zomaato-a64ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbj4RYz9I49UAUnF-e0lYo56eHPf-VR98',
    appId: '1:869303010677:android:0449b3336da8b7fa6aff3c',
    messagingSenderId: '869303010677',
    projectId: 'zomaato-a64ad',
    storageBucket: 'zomaato-a64ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE5l18BKzwHP42EW42LZ9pwrSeVhQcnI0',
    appId: '1:869303010677:ios:d2a0fcab9b6c80dc6aff3c',
    messagingSenderId: '869303010677',
    projectId: 'zomaato-a64ad',
    storageBucket: 'zomaato-a64ad.appspot.com',
    iosClientId: '869303010677-kbdc53f8ph7f6s0gkrlsqgabt8b1ippa.apps.googleusercontent.com',
    iosBundleId: 'com.example.zomatoMeals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE5l18BKzwHP42EW42LZ9pwrSeVhQcnI0',
    appId: '1:869303010677:ios:2be47aee5de9d3dd6aff3c',
    messagingSenderId: '869303010677',
    projectId: 'zomaato-a64ad',
    storageBucket: 'zomaato-a64ad.appspot.com',
    iosClientId: '869303010677-hkvf396s0e2g9erfbpki3r6crbi6dqkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.zomatoMeals.RunnerTests',
  );
}
